### ISSUE TITLE
import files should diff existing file

### ISSUE THREAD

**Issue by n0rad** [neuspaces/terraform-provider-system#2]
When importing a file the plan do not show a diff of the file but only what will be pushed

To ease starting usage of the module, import should show a diff.
To get around it, I'm copying the actual file, applying the plan and run diff on the 2 files to make sure I did not broke something.

**Comment by dominik-lekse** [comment]
@n0rad Thanks for reporting this issue.

When a `system_file` resource was imported, the import did not read the content of the remote file and thus the content was not stored in the state. A post import diff would always show the entire content as changed.

Release [v0.4.0](https://github.com/neuspaces/terraform-provider-system/releases/tag/v0.4.0) supports import of `system_file` resource with explicit import of `content` or `content_sensitive`. 

For details, please review the [system_file import documentation](https://registry.terraform.io/providers/neuspaces/system/latest/docs/resources/file#import).

Looking forward for your feedback if this solves the original issue.

**Comment by n0rad** [comment]
that's a bit weird that you cannot deduce if you need to import as content or sensitive since you should already have one of them declared on the resource, but it's working as documented :+1:
