### ISSUE TITLE
Support changing file content without delete/create

### ISSUE THREAD

**Issue by n0rad** [neuspaces/terraform-provider-system#3]
Changing a file content make it delete/creating the resource. To me this should be done with an update of the resource.

I think it can even be harmful depending on what is using the file in the system to see it disappearing,

I already had one case that is harmful: handling the sudoers file with terraform-provider-system, make it losing right to sudo.

**Comment by dominik-lekse** [comment]
@n0rad Thanks for reporting this issue.

Release [v0.4.0](https://github.com/neuspaces/terraform-provider-system/releases/tag/v0.4.0) supports in-place updates of the attributes `content` or `content_sensitive` without recreating the resource.

Looking forward for your feedback if this solves the original issue.

**Comment by n0rad** [comment]
looks good !
