### ISSUE TITLE
Please consider unlimit the service unit type in system_service_systemd

### ISSUE THREAD

**Issue by fsdrw08** [neuspaces/terraform-provider-system#6]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If an issue is assigned to a user, that user is claiming responsibility for the issue.

### New or Affected Resource(s)

* system_service_systemd

For now, the resource `system_service_systemd` only able to manage the systemd unit type of `.service`, there are many other type of systemd unit might able to be manged by this resources, e.g. systemd unit type of `.mount`, `.path`, I think this resource should also able to manage them.

Please consider include these kinds of the unit type in system_service_systemd, or just remove the hard code of `.service` in the following 
code of `fmt.Sprintf` in this file [internal/client/service_systemd.go](https://github.com/neuspaces/terraform-provider-system/blob/510e3d03db2fbe34b9ce19f2bb23b7a4b246090e/internal/client/service_systemd.go)

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# Consider multiple alternatives for a discussion
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by dominik-lekse** [comment]
@fsdrw08 Thanks for reporting this feature request.

Indeed, the provider could support other system unit types than `service`.

According to the [systemd.unit](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html) documentation, supported unit types are `service`, `socket`, `device`, `mount`, `automount`, `swap`, `target`, `path`, `timer`, `slice`, or `scope`.

The current resource name to manage systemd service units in the provider is `system_service_systemd`. The name includes the term `service` and therefore I would not consider adding support for additional unit types in `system_service_systemd`.

The proposal is to add a new resource `system_systemd_unit` which supports all systemd unit types. The following snippet shows an example of what this resource could look like.

```
resource "system_systemd_unit" "helloworld" {
  type    = "timer" # valid values are "service", "socket", "device", "mount", "automount", "swap", "target", "path", "timer", "slice", "scope"
  name    = "helloworld"
  enabled = true
  status  = "started"
}
```

Would you be available to contribute the implementation and/or test cases?

**Comment by dominik-lekse** [comment]
Release [v0.5.0](https://github.com/neuspaces/terraform-provider-system/releases/tag/v0.5.0) adds the new resource `system_systemd_unit`.

Looking forward for your feedback on the new resource.

**Comment by fsdrw08** [comment]
the new resource works fine! much thanks!
it woule perfect if these systemd resources support in `--user` level
