### ISSUE TITLE
Please support systemd timer

### ISSUE THREAD

**Issue by mkkot** [neuspaces/terraform-provider-system#7]
It seems that service and timer are almost the same. Currently I'm using ansible provider to manage timers, but ansible is not capable of displaying changes only when there is a change to make.

**Comment by dominik-lekse** [comment]
@mkkot Thanks for reporting this feature request.

This feature request is a special case of https://github.com/neuspaces/terraform-provider-system/issues/6.

I encourage engaging in the discussion in the referenced issue and will close this issue as a duplicate.
